name: "Say Hello"
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  say-hello:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [20]

    runs-on: ${{ matrix.os }}
    steps:
      - name: "Hello World"
        run: echo "Hello, world!"

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup Node"
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: "Node Version ${{ matrix.os }} - ${{ matrix.node }}"
        run: |
          node --version
          echo "Node Version ${{ matrix.os }} - ${{ matrix.node }}"
          echo "Secret is configured: ${{ secrets.TESTSECRET }}"
          echo "Env Var: ${{ vars.TESTVARIABLE }}"

      - name: "Install dependencies"
        run: npm ci

      - name: "Lint"
        run: npm run lint

      - name: "Typecheck"
        run: npm run typecheck

      - name: "Build with Next.js"
        run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1
          BASE_PATH: /nextjs

      - name: "Check build output"
        run: |
          ls -la
          ls -la .next

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: next-build-${{ matrix.os }}
          path: .next/