name: Test Composite Action

on:
  schedule:
    - cron:  '*/15 * * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run my composite action
        uses: khamzarazzaq/my-composite-action@main
        with:
          name: Khawaja Hamza
          email: khamzarazzaq@conovoinc.com
          phone: 090078601