name: Test Composite Action

on:
  push:
    branches: ["main"]
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run my composite action
        uses: khamzarazzaq/my-composite-action@main
        with:
          name: Khawaja Hamza
          email: khamzarazzaq@conovoinc.com
          phone: 090078601